### ISSUE TITLE
cpu_instrs 2: wrong  pcmem

### ISSUE THREAD

**Issue by ThibaultEbroussard** [robert/gameboy-doctor#12]
In cpu_instrs 2 I got a mismatch at line 151347:

`MINE:   A:04 F:C--- B:01 C:00 D:C7 E:BA H:90 L:00 SP:9000 PC:0051 PCMEM:2E,0F,18,F3`

But when I look into the binary of the ROM, I got:
```
0x0051 C9
0x0052 00
0x0053 00
0x0054 00
```

So I think there is an error because your values must be "PCMEM:C9,00,00,00".

**Comment by elmarsan** [comment]
#11

**Comment by Comba92** [comment]
The cpu_instrs 2 log is totally wrong in multiple areas. Do not use it.

**Comment by robert** [comment]
@Comba92 do you have a correct one you could PR? That would be v helpful.

**Comment by ysawyers** [comment]
> @Comba92 do you have a correct one you could PR? That would be v helpful.

would really like to see this.
