### ISSUE TITLE
Missing Feature: Tell what PREFIX CB was executed

### ISSUE THREAD

**Issue by zachtango** [robert/gameboy-doctor#16]
![image](https://user-images.githubusercontent.com/38231181/233857352-dc935454-6990-4e8f-b914-f8113b3f05e2.png)

See screenshot above that this log just tells the user that the PREFIX CB instruction occurred, not which specific prefix instruction. While I was debugging my emulator, I felt like if the specific prefix instruction had been included, it would save me a lot of time.

I'm looking to add this in a PR when I find the time.

**Comment by robert** [comment]
Great idea, I'd love to have that feature and especially a PR for it. The code's a little gnarly but hopefully it's possible to squeeze it in. Thanks!

**Comment by robert** [comment]
Fixed by https://github.com/robert/gameboy-doctor/pull/19
