### ISSUE TITLE
Script does not return a non-zero exit code on error

### ISSUE THREAD

**Issue by devins2518** [robert/gameboy-doctor#2]
I'm attempting to integrate this into my automated testing for my emulator, but the script does not produce a different error code when it finds an error, making it more difficult to detect errors automatically.

**Comment by robert** [comment]
Good spot! Should be fixed by https://github.com/robert/gameboy-doctor/commit/6efbdaa92a5a16a022870fa13bfabf75f6ec74cc , lmk if still problems.
