### ISSUE TITLE
cpu_instr 8: mismatched instruction from blargg test on line 208109

### ISSUE THREAD

**Issue by ysawyers** [robert/gameboy-doctor#22]
I downloaded the .gb file from https://github.com/retrio/gb-test-roms/blob/master/cpu_instrs/individual/08-misc%20instrs.gb and on line 208109 it says there is a POP AF instruction but I'm seeing that there is instead a NOP at that position instead.

Is the test file for blargg cpu_instr 8 out of date?

**Comment by robert** [comment]
Hey @ysawyers , it's definitely possible that the gameboy-doctor logs are wrong. Did you find out anything that caused you to close this issue?

**Comment by ysawyers** [comment]
> Hey @ysawyers , it's definitely possible that the gameboy-doctor logs are wrong. Did you find out anything that caused you to close this issue?

Yeah, saw it was just a bug on my end. Great tool by the way!
